### ISSUE TITLE
AutocompleteEngine.search() should require an input

### ISSUE THREAD

**Issue by fabiankessler** [fmmfonseca/completely#2]
Currently, the search method accepts
* null (explicitly with the annotation @Nullable)
* empty string

Running a search(null) throws an NPE, so that's against the documentation.
Running a search("") returns 0 results, that's as expected.

Instead of fixing the NPE case, I recommend not permitting both of those inputs. Why? They are user errors. It's useless to search for nothing, it's clear from the start that nothing can be found. Therefore the best is to document this and to throw an IllegalArgumentException.

**Comment by fabiankessler** [comment]
I have first committed a proof of the issue, and then my suggested change.

**Comment by fmmfonseca** [comment]
The null search might or not make sense... One might have a analyzer that transforms nulls to something else... That was the idea anyway.

**Comment by fmmfonseca** [comment]
As of version 0.3.0 the search method no longer allows a null argument.
