### ISSUE TITLE
Sorting concept

### ISSUE THREAD

**Issue by fabiankessler** [fmmfonseca/completely#3]
Currently sorting works using the Comparator in the AutocompleteEngine.
There can be a default comparator, and one can be given to the search() method to override the default.

After sorting, there is also the limit feature to cut the result at some point.

This flexibility requires 4 public methods in the interface right now.

Unfortunately, the Comparator logic is not enough for my use case. And I believe that also for others it won't be. 

No one is forced to use it, it can be left as null, and then a custom sorting can be applied after searching in the user's code.

What I need is to include the search query in the comparison. It is not enough to just look at the results isolated.

**Comment by fabiankessler** [comment]
One possibility is to build this feature into the AutocompleteEngine, so that the user could choose between the sorting using a Comparator or using a RecordSorter. But that causes an explosion of api methods. 

Another option is to replace the Comparator with this, keeping 4 api methods.

And yet another is to remove the Comparator out of the api. Then the searching is separate from the sorting and limiting.

**Comment by fmmfonseca** [comment]
The enhancement of sorting logic is something I have considered before but I'm not sure about the implementation yet. My first thought was to have the Index implementations return a SearchResult wrapper with a match score, and have the AutocompleteEngine sort/trim/unwrap it.

I shall give some thought to it.

**Comment by fmmfonseca** [comment]
I would like to enhance both the sorting and the merging, I don't have any implementation yet, but my idea is the following.

As you suggested, the predefined score is not enough, it needs to be dynamically assigned after the search. Contrary to what I first suggested, one cannot assume the Indexes are able to return a meaningful matching score. And I will argue that for the scoring function, more important than the original query is the list of tokens that matched the record. Currently all returned records have to match all tokens, but that's something I would like to change too with custom merging strategies. It should be possible for example to return records present in an arbitrary number of tokens, the typical case would be N-1.

**Comment by fmmfonseca** [comment]
As of version 0.3.0 the FuzzyIndex implementations now return a ScoredObject. As the name suggests, this class is a decorator for scoring results, according to the similarity between the query and the indexed token. A score which can then be used to improve the sorting of the results.
