### ISSUE TITLE
Upload to Maven Central

### ISSUE THREAD

**Issue by czyzby** [fmmfonseca/completely#5]
It would be great if you could include this library as Maven-style dependency into your project without having to clone and "install" it locally. Uploading it to Maven Central - or one of its equivalents/mirrors - would certainly help.

**Comment by fmmfonseca** [comment]
It's a good point, will need a new namespace though.

**Comment by fmmfonseca** [comment]
The library is now available in the central repository.

<dependency>
    <groupId>com.miguelfonseca.completely</groupId>
    <artifactId>completely-core</artifactId>
    <version>0.5.0</version>
</dependency>
