### ISSUE TITLE
Regarding reverse searching

### ISSUE THREAD

**Issue by nikhil-dhiman** [fmmfonseca/completely#6]
I have a string to get indexed
a. [ Panasonic lcd item] [ SampleRecord that i saved [ count:10, location: delhi]]
b. [Iphone 7 buy ]  [ SampleRecord that i saved [ count:100, location: delhi]]
c. [5 seater sofa set ]  [ SampleRecord that i saved [ count:50, location: new york]]
d. [iphone 7 buy]  [ SampleRecord that i saved [ count:400, location: jersey]]
Here count is no. of times particular text is searched, and location is in which location this search is made.

So i want to search like this "Top 100 searches made in delhi"

Your code should return me 'a' 'b' record not 'c','d'

and also if someone searches for iphone 7 delhi, should return 'c' 'd'
Can you suggest me how to do this via your code.

**Comment by fmmfonseca** [comment]
You should index both description and location. To do so, you need to create your own Indexable implementation.
As for the views count, the library supports both sorting and limiting the results.

**Comment by nikhil-dhiman** [comment]
@fmmfonseca : I made 2 entries in search
engine.add("City Delhi");
engine.add("City Delhi");

when i did engine.search("City Delhi") --> Returns me array[City Delhi, City Delhi]. Should it not return me just 1
