### ISSUE TITLE
Regarding Top 10 results

### ISSUE THREAD

**Issue by nikhil-dhiman** [fmmfonseca/completely#7]
Can your logic be tweaked and return me top K results...

**Comment by fmmfonseca** [comment]
The AutocompleteEngine has a search method that accepts a `String query` and a `int limit` parameter. Additionally, the elements can be sorted according to a `Comparator<ScoredObject<T>> comparator`.

**Comment by nikhil-dhiman** [comment]
Sorry i forgot to mention.. no query parameter... Just give me top 10 results...

**Comment by fmmfonseca** [comment]
The underlying data structure indexes elements by text, and the only way to retrieve them is by issuing a query.
